// Auto-generated by deploy script — DO NOT EDIT MANUALLY
export const LENDING_ADDRESSES = {
  Stablecoin:  "0x0B306BF915C4d645ff596e518fAf3F9669b97016",
  MockWETH:    "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1",
  LendingPool: "0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE",
};

export const NETWORK_CONFIG = {
  chainId:   "1337",
  chainName: "Localhost 8545",
  rpcUrl:    "http://127.0.0.1:8545",
};
