/**
 * COMP5521 Lending Protocol - Deploy Script
 *
 * Deploys:
 *  1. Stablecoin (C5D) - 1 C5D = $1 USD
 *  2. MockWETH         - 1 WETH = $2000 USD
 *  3. LendingPool      - core lending protocol
 *
 * Then configures the LendingPool:
 *  - Adds C5D and WETH as supported assets
 *  - Mints initial tokens to deployer for testing
 *
 * Run: NODE_TLS_REJECT_UNAUTHORIZED=0 npx hardhat run scripts/deploy.cjs --network localhost --config hardhat.config.cjs
 */

const hre = require("hardhat");
const fs  = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("\n=== COMP5521 Lending Protocol Deployment ===");
  console.log("Deployer:", deployer.address);
  console.log("Network:", hre.network.name);

  // ── 1. Deploy Stablecoin (C5D) ──────────────────────────────────────────
  console.log("\n[1/3] Deploying Stablecoin (C5D)...");
  const Stablecoin = await hre.ethers.getContractFactory("Stablecoin");
  const stablecoin = await Stablecoin.deploy();
  await stablecoin.waitForDeployment();
  console.log("  C5D deployed to:", await stablecoin.getAddress());

  // ── 2. Deploy MockWETH ──────────────────────────────────────────────────
  console.log("\n[2/3] Deploying MockWETH...");
  const MockWETH = await hre.ethers.getContractFactory("MockWETH");
  const weth = await MockWETH.deploy();
  await weth.waitForDeployment();
  console.log("  WETH deployed to:", await weth.getAddress());

  // ── 3. Deploy LendingPool ───────────────────────────────────────────────
  console.log("\n[3/3] Deploying LendingPool...");
  const LendingPool = await hre.ethers.getContractFactory("LendingPool");
  const lendingPool = await LendingPool.deploy();
  await lendingPool.waitForDeployment();
  console.log("  LendingPool deployed to:", await lendingPool.getAddress());

  // ── 4. Configure LendingPool ─────────────────────────────────────────────
  console.log("\n[4/4] Configuring LendingPool...");

  const PRECISION = hre.ethers.parseEther("1"); // 1e18

  // Add C5D:
  //   LTV = 80%,  LiqThreshold = 85%
  //   baseRate = 2% per year,  slope = 10% per year at 100% utilization
  //   price = $1.00
  await lendingPool.addSupportedToken(
    await stablecoin.getAddress(),
    80,                            // LTV 80%
    85,                            // Liquidation threshold 85%
    2,                             // base rate 2% APR
    10,                            // slope 10% APR
    hre.ethers.parseEther("1"),    // $1.00 USD
  );
  console.log("  C5D added to LendingPool");

  // Add WETH:
  //   LTV = 75%,  LiqThreshold = 80%
  //   baseRate = 2% per year,  slope = 20% per year at 100% utilization
  //   price = $2000.00
  await lendingPool.addSupportedToken(
    await weth.getAddress(),
    75,                                      // LTV 75%
    80,                                      // Liquidation threshold 80%
    2,                                       // base rate 2% APR
    20,                                      // slope 20% APR
    hre.ethers.parseEther("2000"),           // $2000 USD
  );
  console.log("  WETH added to LendingPool");

  // ── 5. Mint test tokens to first 5 accounts (for demo) ───────────────────
  console.log("\n[5] Minting initial test tokens to first 5 accounts...");
  const allSigners = await hre.ethers.getSigners();
  const demoAccounts = allSigners.slice(0, 5);
  for (const acc of demoAccounts) {
    await stablecoin.mint(acc.address, hre.ethers.parseEther("100000")); // 100k C5D
    await weth.mint(acc.address, hre.ethers.parseEther("50"));           // 50 WETH
    console.log("  Minted to", acc.address);
  }

  // ── 6. Save addresses ────────────────────────────────────────────────────
  const addresses = {
    Stablecoin:  await stablecoin.getAddress(),
    MockWETH:    await weth.getAddress(),
    LendingPool: await lendingPool.getAddress(),
    deployer:    deployer.address,
    network:     hre.network.name,
    chainId:     1337,
    deployedAt:  new Date().toISOString(),
  };

  // Write to project root
  const addressFile = path.join(__dirname, "..", "deployed-addresses.json");
  fs.writeFileSync(addressFile, JSON.stringify(addresses, null, 2));
  console.log("\n✅ Addresses saved to deployed-addresses.json");

  // Also write a frontend-ready config
  const frontendConfig = `// Auto-generated by deploy script — DO NOT EDIT MANUALLY
export const LENDING_ADDRESSES = {
  Stablecoin:  "${addresses.Stablecoin}",
  MockWETH:    "${addresses.MockWETH}",
  LendingPool: "${addresses.LendingPool}",
};

export const NETWORK_CONFIG = {
  chainId:   "1337",
  chainName: "Localhost 8545",
  rpcUrl:    "http://127.0.0.1:8545",
};
`;
  const frontendConfigPath = path.join(__dirname, "..", "frontend", "src", "config", "lendingContracts.js");
  fs.writeFileSync(frontendConfigPath, frontendConfig);
  console.log("✅ Frontend config saved to frontend/src/config/lendingContracts.js\n");

  // Summary
  console.log("==============================================");
  console.log("Deployment complete!");
  console.log("  C5D:         ", addresses.Stablecoin);
  console.log("  WETH:        ", addresses.MockWETH);
  console.log("  LendingPool: ", addresses.LendingPool);
  console.log("==============================================\n");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
